{{if eq .Values.templateApp "user-template"}} 
apiVersion: batch/v1
kind: Job
metadata:
  name: argocd
spec:
  template:
    spec:
      containers:
      - name: user-db-container
        image: mohamedgomaa567/microservice-user-db:1
      restartPolicy: Never
  backoffLimit: 4
{{- end}}
