{{- $service:= .service}}
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: {{ $.Values.container.name }}-vs
  namespace: cloud-test
spec:
  hosts:      # which incoming host are we applying the proxy rules to???
    - {{ printf "%s.mg.com" $service }}
  gateways:
    - ingress-internal-gateway
  http:
    - match:
        - headers:  # IF
            service:
              exact: {{ $service }}
      route: # THEN
        - destination:
            host: {{ $.Values.service.name }}
            subset: {{ $service }}-sets
---

kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: {{ $service }}-dr
  namespace: cloud-test
spec:
  host: {{ $.Values.service.name }}
  subsets:
    - labels:
        app: {{ $.Values.templateApp }}
      name: {{ $service }}-sets
