kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: {{ .Values.domain }}-vs
  namespace: argocd
spec:
  hosts:      # which incoming host are we applying the proxy rules to???
    - {{ printf "%s.mg.com" .Values.domain }}
  gateways:
    - ingress-internal-gateway
  http:
    - match:
        - headers:  # IF
            service:
              exact: {{ .Values.domain }}
      route: # THEN
        - destination:
            host: {{ .Values.service.name }}
            subset: {{ .Values.domain }}-sets
---

kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: {{ .Values.domain }}-dr
  namespace: argocd
spec:
  host: {{ .Values.service.name }}
  subsets:
    - labels:
        app: {{ .Values.templateApp }}
      name: {{ .Values.domain }}-sets
