kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: {{ .Values.container.name }}-vs
  namespace: cloud-test
spec:
  hosts:      # which incoming host are we applying the proxy rules to???
    - {{ printf "%s.mg.com" .Values.container.name }}
  gateways:
    - ingress-internal-gateway
  http:
    - match:
        - headers:  # IF
            service:
              exact: {{ .Values.container.name }}
      route: # THEN
        - destination:
            host: {{ .Values.service.name }}
            subset: {{ .Values.container.name }}-sets
---

kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: {{ .Values.container.name }}-dr
  namespace: cloud-test
spec:
  host: {{ .Values.service.name }}
  subsets:
    - labels:
        app: {{ .Values.templateApp }}
      name: {{ .Values.container.name }}-sets
